List previous orders
cybe-m1/tp_final_commandes_Anatole_de_Chauveron_Anthony_Quere pull request #25
Opened 2021-12-01 09:31 UTC by Anatole-DC

2021-12-01 09:32 UTC, Anatole-DC commented
J'ai merge ta branche et j'ai rajouté une feature dedans vu que c'est lié au commandes plus qu'aux clients, mais si c'est pas bon, dis-moi avant que je fasse tout avec cette méthode

2021-12-01 10:03 UTC, Anthony-Jhoiro requested changes
Je pense que tu peux revoir des trucs. Le plus logqie pour moi c'est plus d'utiliser un chemin  comme /customer/{id}/orders parce que l'on veut littéralement les orders d'un customer plutot que /orders/{id}/orders qui signifie les orders d'une order (ce qui n'a pas beaucoup de sens dans notre cas. Donc je pense qu'il serait interessant de tout bouger dans la partie customer tout en gardant la récupération des orders par client depuis la db dans la partie order à partir d'une nouvelle méthode dans OrderRepository. Hésite pas en cas de problème

2021-12-01 10:03 UTC, Anthony-Jhoiro commented on src/main/java/com/fges/commandes/commandes/order/OrderService.java
> +    }
Write custom query in the repository : what happend if there are 1_000_000 orders in total

2021-12-06 09:03 UTC, Anthony-Jhoiro commented
Pour moi la requete et le service doivent aussi être géré dans la partie customer. Ca pourrait être intéressant d'ajouter une liste d'order dans l'entity customer (en fetch type lazy pour éviter de tout récupérer à chaque fois) et du coup toute la gestion est gérée dans la partie customer. Je pense que c'est plus logique dans le sens où si on veut récupérer la même chose pour un truck, on ne veut pas forcément modifier la partie order.

2021-12-07 11:31 UTC, Anthony-Jhoiro approved these changes

2021-12-07 11:31 UTC, merged